---
title: "record of work on 10-year pregnancy paper"
author: "Steven M. Goodreau"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## May 12, 2020

- Copied over code from GC/CT, now working through from beginning of entire_project step by step.

- a10_import:  removed race mixing (not needed), and initial diagnoses.  Will need to replace the latter with initial pregnancies once we have them

- changed package name, set up NAMESPACE etc.  

## May 28, 2020

Plan today: continue through code step by step, and in the process:
- Remove males
- Redo incidence to reflect detectable pregnancies
- Simplify calibration code dramatically
- Identify full set of questions to return to team with

Tasks completed:
- Changed all setwd references
- removed males from a10_process_inputs.R
- removed males from a10_make_behav_inputs_all_2007.R
- removed a10_process_dx_for_calib altogether 
-- may need to create parallel file depending on age categories for pregnancy data -- it seems that these may come in single-year age categories, so then won't need this step but rather just be combined into age categories more simply
- rewrote a10_calib in numerous ways
- ran calib.pt1 to determine it gave no errors.

## June 18, 2020

Commited lots of old things (must get on top of this!)
Filed tickets
Looked at David's BC data files

## June 19, 2020

Wrote code to import BC data
Wrote code to process BC data
Got as far as multinomial regression for year 2007.  

Need to clean up BC processing code so it's less ugly and repetitive.

### Leave at bottom

Todo:
- change condom to bc throughout
- update costs
- get preg_init

Things to think about:
- need to replace dx input data with detectable pregnancy input data. What form will this come in? By age? By race/ethn?  By single years? All detectable pregs or by outcomes?
- need to decide what to calibrate to exactly - pregs? births?  in school or tot? by race/ethn?
- how to do regressions on BC options?

### Master change list

# Inputs
part_prev_ratio_X    -> nothing             (AND NO LONGER CALIB PARAM)
beta_X2X             -> prob_detpreg_f      (NEW CALIB PARAM?)
diag_init_X          -> preg_init_f         (CALIB TARGET)
condom_use_X         -> bc_use_f            multidimensional?
p_ethn_X             -> nothing
prop_diag_X          -> nothing?
dur_inf_X            -> nothing

# Outputs
n_dx_total_f         -> n_preg_total        CALIBRATION OUTPUT

